Repository THM-ATLAS/vue-frontend, pull requests merged in 2022-05, with the labels that each got.

#88 Managed to connect Frontend to Backend via API
  package-lock.json
  package.json
  src/components/CourseSearchResult.vue
  src/components/MainPage.vue
  src/components/exercises/ExerciseCard.vue
  src/components/exercises/feedback/FeedbackList.vue
  src/components/exercises/feedback/FeedbackModal.vue
  src/components/exercises/submissions/NewSubmission.vue
  src/components/helpers/SkipToContent.vue
  src/helpers/types.ts
  src/services/API.ts
  src/services/LoginService.js
  src/services/ModuleService.js
  src/services/TaskService.js
  src/services/UserService.js
Labels: enhancement, help wanted

#118 Added cursor animation
  src/components/navigation/navbar/NavbarBase.vue
Labels: enhancement, good first issue

#139 Exercise edits are now saved and a conformation dialog pops up when…
  src/components/exercises/ExerciseEditor.vue
  src/i18n/de.ts
  src/i18n/en.ts
  src/services/ExerciseService.ts
Labels: bug, enhancement

#140 Added back button to individual course pages
  src/components/CourseMainPage.vue
Labels: enhancement
